### ISSUE TITLE
definition of the index of password list occurs at an incorrect position

### ISSUE THREAD

**Issue by soh0ro0t** [lochv/telnet-bruteforce#2]
> def optimus(ip):
    if not is_open_port_23(ip):
        sys.exit(1)
    logging.debug("O: " + ip)
    # print "try ", ip
    i = 0
    for key in dic:
        values = dic[key]
        while i < len(values):

I think there is an error when defining variable 'i', which is actually defined like this:

> def optimus(ip):
    if not is_open_port_23(ip):
        sys.exit(1)
    logging.debug("O: " + ip)
    # print "try ", ip
    # i = 0
    for key in dic:
        i = 0
        values = dic[key]
        while i < len(values):

**Comment by lochv** [comment]
oh, my bad, thank!
fixed
